### PR TITLE
add Chrome support

### PR DESCRIPTION
**Pull request by eyanq**
Hi @ghandic, I've added some changes to the code to support Chrome browser.

### CODE REVIEW

**Review by ghandic — COMMENTED** [review]
Great, thanks for the pull request! What is the private key for?

**Comment by eyanq** [comment]
The pem file was automatically generated when I packaging the extension.

**Comment by ghandic** [comment]
I don’t think it’s ideal storing a private key on github, will it work without the pem?

**Comment by eyanq** [comment]
Hi @ghandic, I tried the extension without the pem file and it works ok to me. just created a new commit and removed the pem file.

**Pull request merged**
